# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

redis = "12800"

[train]
resume = false
epoch = 80
output_dir = "./outputs/rl"
epsilon = 1e-6
optm_name = "AdamW"
optm_lr = 2e-6
optm_impl = "fused"
optm_weight_decay = 0.01
optm_betas = [ 0.9, 0.95,]
optm_warmup_steps = 20
optm_grad_norm_clip = 1.0
async_tp_enabled = false
compile = false
master_dtype = "float32"
param_dtype = "bfloat16"
fsdp_reduce_dtype = "float32"
fsdp_offload = false
fsdp_reshard_after_forward = "default"
train_batch_per_replica = 128
sync_weight_interval = 1

[rollout]
gpu_memory_utilization = 0.7
enable_chunked_prefill = false
max_response_length = 6144
n_generation = 8
batch_size = 4
quantization = "none"

[policy]
model_name_or_path = "nvidia/Cosmos-Reason1-7B"
model_max_length = 10240
model_gradient_checkpointing = true

[logging]
logger = ['console', 'wandb']
project_name = "cosmos_reason1"
experiment_name = "post_training/rl"

[train.train_policy]
type = "grpo"
dataset.name = "nvidia/Cosmos-Reason1-RL-Dataset"
dataset.subset = "robovqa"
dataset.split = "rl"
enable_dataset_cache = false
dataloader_num_workers = 4
dataloader_prefetch_factor = 4
prompt_column_name = "qa_pairs"
reward_function = ["single_choice", "format"]
temperature = 0.9
epsilon_low = 0.2
epsilon_high = 0.2
kl_beta = 0.0
mu_iterations = 1
min_filter_prefix_tokens = 1
mini_batch = 2

[train.ckpt]
enable_checkpoint = true
save_freq = 100
max_keep = 2
save_mode = "async"


[rollout.parallelism]
n_init_replicas = 1
tp_size = 2
pp_size = 1

[policy.parallelism]
n_init_replicas = 1
tp_size = 1
cp_size = 1
dp_shard_size = 2
pp_size = 1
dp_replicate_size = 1
cp_rotate_method = "allgather"
